// <auto-generated />
using System;
using FitForLife.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FitForLife.Migrations
{
    [DbContext(typeof(FitnessContext))]
    [Migration("20200912152740_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FitForLife.Models.Members", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("cell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("zip")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ID");

                    b.ToTable("Membership");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            email = "lbalbach@nmc.edu",
                            gender = "prefer not to disclose",
                            name = "Lisa Balbach"
                        },
                        new
                        {
                            ID = 2,
                            gender = "prefer not to disclose",
                            name = "Shaggy Rogers"
                        },
                        new
                        {
                            ID = 3,
                            gender = "prefer not to disclose",
                            name = "Daphne Blake"
                        });
                });

            modelBuilder.Entity("FitForLife.Models.Stats", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MembersID")
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<float>("height")
                        .HasColumnType("real");

                    b.Property<DateTime>("statDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("weight")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("MembersID");

                    b.ToTable("Statistics");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            MembersID = 1,
                            age = 57,
                            height = 64f,
                            statDate = new DateTime(2020, 9, 12, 11, 27, 40, 146, DateTimeKind.Local).AddTicks(5194),
                            weight = 118f
                        },
                        new
                        {
                            ID = 2,
                            MembersID = 2,
                            age = 29,
                            height = 70f,
                            statDate = new DateTime(2020, 9, 12, 11, 27, 40, 150, DateTimeKind.Local).AddTicks(7828),
                            weight = 150f
                        },
                        new
                        {
                            ID = 3,
                            MembersID = 3,
                            age = 22,
                            height = 66f,
                            statDate = new DateTime(2020, 9, 12, 11, 27, 40, 150, DateTimeKind.Local).AddTicks(7941),
                            weight = 125f
                        });
                });

            modelBuilder.Entity("FitForLife.Models.Stats", b =>
                {
                    b.HasOne("FitForLife.Models.Members", "Members")
                        .WithMany()
                        .HasForeignKey("MembersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
